// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDwN2aWMSdaxwmKzQYl7T5F7zYCu2Ol7U',
    appId: '1:708962562307:web:ce636cf38b33b037277936',
    messagingSenderId: '708962562307',
    projectId: 'bhattimandu',
    authDomain: 'bhattimandu.firebaseapp.com',
    storageBucket: 'bhattimandu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQf2JCHkVjCs8UZHHq3fM5_s_9DHJfho0',
    appId: '1:708962562307:android:74a05f97fd27b8ec277936',
    messagingSenderId: '708962562307',
    projectId: 'bhattimandu',
    storageBucket: 'bhattimandu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe-HVj3V_zLxiGUBzR868yRQ23y-bw5yU',
    appId: '1:708962562307:ios:953d14ef0eb91ba8277936',
    messagingSenderId: '708962562307',
    projectId: 'bhattimandu',
    storageBucket: 'bhattimandu.firebasestorage.app',
    iosBundleId: 'com.example.bhattimandu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDwN2aWMSdaxwmKzQYl7T5F7zYCu2Ol7U',
    appId: '1:708962562307:web:ce636cf38b33b037277936',
    messagingSenderId: '708962562307',
    projectId: 'bhattimandu',
    authDomain: 'bhattimandu.firebaseapp.com',
    storageBucket: 'bhattimandu.firebasestorage.app',
  );
}
